CSS Framework CA
eskiltorset/css-frameworks pull request #1
Opened 2023-08-31 17:15 UTC by eskiltorset

I accidentally did all my work in sass-setup rather than cs-fw branch. Sorry about that.
inside this branch i have commited my CSS Framework project - with a login page, feed and profile page made by using Bootstrap and SASS.

2023-09-01 11:11 UTC, sulenchy requested changes
@eskiltorset see my comments above

2023-09-01 11:11 UTC, sulenchy commented on src/scss/styles.scss
> +.card {
There is a class in Bootstrap called card. You can extend it if you like. See the example in the https://content.noroff.dev/css-frameworks/bootstrap-with-sass.html#bootstrap-variables

2023-09-01 11:11 UTC, sulenchy commented on src/scss/_variables.scss
> +$secondary-colour: rgb(199, 98, 98);
These are your custom variables that have nothing to do with bootstrap. You can simply get an existing variable in Bootstrap and override its value with your new value. See an example

```$blue:    #5d95e8;
$indigo:  #916fc8;
$purple:  #5d3b9c;
$pink:    #ab4578;
$red:     #fa2f44;
$orange:  #ffa053;
$yellow:  #ffdf7e;
$green:   #4fe49e;
$teal:    #9fffe2;
$cyan:    #8eecff;```

2023-09-03 19:27 UTC, eskiltorset commented on src/scss/_variables.scss
> +$secondary-colour: rgb(199, 98, 98);
Hey, i have resolved it now.

2023-09-03 19:30 UTC, eskiltorset commented on src/scss/styles.scss
> +.card {
Nothing i'd like to extend about the .card class - but now i'll know!

2023-09-03 19:31 UTC, merged